services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    hostname: leferrei.42.fr
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - $HOME/data/wordpress:/var/www
    networks:
      - 42net
    restart: unless-stopped

  database:
    build: ./requirements/mariadb
    container_name: db
    env_file:
      - .env
    volumes:
      - $HOME/data/mariadb/db:/var/lib/mysql
    networks:
      - 42net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh healthchecker.sh" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 0s

  wordpress:
    build: ./requirements/wordpress
    depends_on:
      database:
        condition: service_healthy
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - $HOME/data/wordpress:/var/www
    networks:
      - 42net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh healthchecker.sh" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 0s

networks:
  42net:
    driver: bridge