services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    hostname: leferrei.42.fr
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - $HOME/data/wordpress:/var/www/php
    networks:
      - 42net
    restart: unless-stopped

  database:
    build: ./requirements/mariadb
    container_name: db
    env_file:
      - .env
    volumes:
      - $HOME/data/mariadb/db:/var/lib/mysql
    networks:
      - 42net
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    # depends_on:
    #   - database
    working_dir: /var/www/php
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - $HOME/data/wordpress:/var/www/php
    networks:
      - 42net
    restart: unless-stopped

networks:
  42net:
    driver: bridge