services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
  database:
    build: ./requirements/mariadb
    container_name: db
    env_file:
      - .env
  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - database
    container_name: wordpress
    env_file:
      - .env
networks:
  42net:
    driver: bridge