echo "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;" | mariadb
echo "CREATE USER IF NOT EXISTS $MARIADB_USER@localhost IDENTIFIED BY '$MARIADB_PASSWORD';" | mariadb
echo "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MARIADB_USER'@localhost;" | mariadb
echo "FLUSH PRIVILEGES;" | mariadb
echo "ALTER USER root@localhost IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';" | mariadb